Repository SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer, pull requests merged in 2022-06, with the labels that each got.

#74 312: Add accountId in the Domestic Scheduled Payment Intent
  config/defaults/secure-open-banking/managed-objects/domesticScheduledPaymentIntent.json
Labels: enhancement

#85 Issue/292 GitHub action image pr number
  .github/workflows/merge.yml
Labels: bug

#86 353: Setup SBAT developer environment
  config/viper/viper-default-configuration.yaml
Labels: deployment, configuration

#87 354: update standing order intent name
  config/defaults/secure-open-banking/managed-objects/domesticStandingOrderIntent.json
  config/defaults/secure-open-banking/policy-evaluation-script.js
Labels: enhancement, configuration
